version: '3'
services:
    flask:
        build: .
        volumes:
            - .:/flaskapp
        working_dir: /flaskapp
        command: uwsgi --ini /flaskapp/app.ini
              
    nginx:
        image: nginx:alpine
        ports:
            - "8880:80"
        volumes:
            - .:/flaskapp
            - ./conf.d:/etc/nginx/conf.d
